### ISSUE TITLE
function from button

### ISSUE THREAD

**Issue by sabas1080** [marcoschwartz/aREST_UI#6]
Hi

I cant call function from button?

Is there any example?

Thanks

**Comment by marcoschwartz** [comment]
Hi! That's not supported yet indeed. Marking this a feature request :)

**Comment by brynnbp** [comment]
@sabas1080 just as an FYI, this has been added but isn't documented yet it seems. 

`rest.callFunction("urlPathToGoTo", "push")`

It looks like "push" is the only option set for second parameter. I assume "push" means pushing a button, since it generates a button to push for you. 

I plan to look into simply allowing callbacks to be called for all UI items, not sure when I'll get time for it.

**Comment by anwarbashir** [comment]
I tried this but I get jquery-2.1.3.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #fn_push_192.168.0.8/6/1

Also when I try to add a second rest.button(6) my ESP32 continually resets. 

Will I be able to add controls in due course?

**Comment by sabas1080** [comment]
Thanks!
